sudo: false

language:
  - cpp

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data

script:
  - cd Code/sim-knx
  - mkdir build-travis
  - cd build-travis
  - cmake ..
  - make
  - cd test
  - ./runUnitTests