sudo: false

language:
  - cpp

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cmake-data
      - g++-5

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

script:
  - cmake --version
  - cd Code/sim-knx
  - mkdir build-travis
  - cd build-travis
  - cmake ..
  - make
  - cd test
  - ./runUnitTests